data:
  dataset_type: "eegbci"  # 使用EEGBCI数据集
  cache_dir: "data"       # 数据缓存目录
  batch_size: 32
  num_workers: 4
  sampling_rate: 160      # EEGBCI数据集的采样率
  preprocessing:
    low_freq: 7.0        # 带通滤波器低频截止频率
    high_freq: 30.0      # 带通滤波器高频截止频率
    window_size: 640     # 时间窗口大小（4秒 * 160Hz）
    stride: 320          # 时间窗口滑动步长（2秒 * 160Hz）

model:
  name: "EEGNet"
  input_channels: 64     # EEGBCI的EEG通道数
  dropout_rate: 0.5
  kernel_length: 32      # 减小卷积核长度
  num_filters: 8
  pool_size: 4          # 减小池化大小
  num_classes: 4        # EEGBCI的运动想象类别数

training:
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam"
  scheduler:
    name: "cosine"
    T_max: 100
    eta_min: 0.00001
  early_stopping:
    patience: 10
    min_delta: 0.001
  checkpoint_dir: "checkpoints"
  use_wandb: true      # 是否使用Weights & Biases进行实验跟踪

evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "kappa"
  visualization:
    confusion_matrix: true
    roc_curve: true
    learning_curves: true
    topographic_maps: true 