data:
  dataset_type: "eegbci"  # 使用EEGBCI数据集
  cache_dir: "data"       # 数据缓存目录
  batch_size: 64          # 增加批量大小提高训练稳定性
  num_workers: 0          # 暂时不使用多进程加载
  sampling_rate: 160      # EEGBCI数据集的采样率
  preprocessing:
    low_freq: 8.0         # 调整到mu节律起始频率
    high_freq: 30.0       # 保持beta节律上限
    window_size: 800      # 增加窗口大小以捕获更多时间信息
    stride: 400           # 相应调整步长
  augmentation:
    enabled: true         # 启用数据增强
    p_noise: 0.5          # 添加噪声的概率
    p_flip: 0.3           # 信号翻转的概率
    p_mask: 0.3           # 时间掩码的概率
    noise_scale: 0.1      # 高斯噪声的标准差
    mask_ratio: 0.1       # 掩码比例
  spatial_filter:
    enabled: true         # 启用空间滤波
    type: "csp"           # 使用CSP滤波器
    n_components: 16      # CSP组件数量
    attention: true       # 使用空间注意力

model:
  name: "eegnet"
  input_channels: 64      # EEGBCI的EEG通道数
  dropout_rate: 0.4       # 降低dropout以减少正则化
  kernel_length: 64       # 增加卷积核长度以捕获更长时间依赖
  num_filters: 12         # 适当减少滤波器数量
  pool_size: 2           # 减小池化大小减少信息损失
  num_classes: 4         # EEGBCI的运动想象类别数

training:
  epochs: 500            # 增加总轮次
  learning_rate: 0.001   # 保持较高的初始学习率
  weight_decay: 0.0001    # 降低权重衰减
  optimizer: "adamw"      # 使用AdamW优化器
  scheduler:
    name: "cosine"
    T_max: 500            # 匹配epochs
    eta_min: 0.00001      # 保持最小学习率
  early_stopping:
    patience: 100          # 增加早停耐心值
    min_delta: 0.0005    # 降低提升阈值
  checkpoint_dir: "checkpoints"
  use_wandb: true        # 使用Weights & Biases进行实验跟踪

monitoring:
  metrics:
    train:              # 训练集指标
      - name: "loss"
        summary: "min"
      - name: "accuracy"
        summary: "max"
      - name: "f1"
        summary: "max"
      - name: "precision"
        summary: "max"
      - name: "recall"
        summary: "max"
      - name: "kappa"
        summary: "max"
    val:                # 验证集指标
      - name: "loss"
        summary: "min"
      - name: "accuracy"
        summary: "max"
      - name: "f1"
        summary: "max"
      - name: "precision"
        summary: "max"
      - name: "recall"
        summary: "max"
      - name: "kappa"
        summary: "max"
  
  visualizations:
    plots:              # 图表配置
      - name: "Loss"
        type: "line"
        metrics: ["train/loss", "val/loss"]
      - name: "Accuracy"
        type: "line"
        metrics: ["train/accuracy", "val/accuracy"]
      - name: "F1 Score"
        type: "line"
        metrics: ["train/f1", "val/f1"]
      - name: "Precision"
        type: "line"
        metrics: ["train/precision", "val/precision"]
      - name: "Recall"
        type: "line"
        metrics: ["train/recall", "val/recall"]
      - name: "Kappa"
        type: "line"
        metrics: ["train/kappa", "val/kappa"]
      - name: "Learning Rate"
        type: "line"
        metric: "learning_rate"
    
    performance:        # 性能评估图
      confusion_matrix:
        enabled: true
        frequency: 5    # 每5个epoch绘制一次
      roc_curve:
        enabled: true
      pr_curve:
        enabled: true
    
    logging:           # 日志配置
      tensorboard: true
      wandb: true
      save_checkpoints: true
      checkpoint_frequency: 1  # 每个epoch保存一次

evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "kappa"
  visualization:
    confusion_matrix: true
    roc_curve: true
    learning_curves: true
    topographic_maps: true 