data:
  dataset_name: "eeg-dataset"  # Hugging Face数据集名称
  batch_size: 32
  num_workers: 4
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  sampling_rate: 250  # Hz

model:
  name: "EEGNet"
  input_channels: 64  # EEG通道数
  dropout_rate: 0.5
  kernel_length: 64
  num_filters: 8
  pool_size: 8
  num_classes: 4  # 分类任务的类别数

training:
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam"
  scheduler:
    name: "cosine"
    T_max: 100
    eta_min: 0.00001
  early_stopping:
    patience: 10
    min_delta: 0.001
  checkpoint_dir: "checkpoints"
  use_wandb: true  # 是否使用Weights & Biases进行实验跟踪

evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
  visualization:
    confusion_matrix: true
    roc_curve: true
    learning_curves: true 