data:
  dataset_type: "eegbci"
  cache_dir: "data"
  batch_size: 16
  num_workers: 0
  sampling_rate: 160
  preprocessing:
    low_freq: 8.0
    high_freq: 30.0
    window_size: 800
    stride: 400
  augmentation:
    enabled: true
    p_noise: 0.3
    p_flip: 0.2
    p_mask: 0.2
    noise_scale: 0.05
    mask_ratio: 0.1
  spatial_filter:
    enabled: true
    type: "csp"
    n_components: 16
    attention: true

model:
  name: "eeglstm"
  input_channels: 64
  hidden_dim: 256
  num_layers: 2
  num_classes: 4
  dropout_rate: 0.3
  bidirectional: true

training:
  epochs: 300
  learning_rate: 0.0001
  weight_decay: 0.001
  optimizer: "adamw"
  scheduler:
    name: "cosine"
    T_max: 300
    eta_min: 0.000001
  early_stopping:
    patience: 50
    min_delta: 0.001
  gradient_clipping:
    max_norm: 1.0
  checkpoint_dir: "checkpoints/lstm"
  use_wandb: true

monitoring:
  metrics:
    train:
      - name: "loss"
        summary: "min"
      - name: "accuracy"
        summary: "max"
      - name: "f1"
        summary: "max"
      - name: "precision"
        summary: "max"
      - name: "recall"
        summary: "max"
      - name: "kappa"
        summary: "max"
    val:
      - name: "loss"
        summary: "min"
      - name: "accuracy"
        summary: "max"
      - name: "f1"
        summary: "max"
      - name: "precision"
        summary: "max"
      - name: "recall"
        summary: "max"
      - name: "kappa"
        summary: "max"
  
  visualizations:
    plots:
      - name: "Loss"
        type: "line"
        metrics: ["train/loss", "val/loss"]
      - name: "Accuracy"
        type: "line"
        metrics: ["train/accuracy", "val/accuracy"]
      - name: "F1 Score"
        type: "line"
        metrics: ["train/f1", "val/f1"]
      - name: "Precision"
        type: "line"
        metrics: ["train/precision", "val/precision"]
      - name: "Recall"
        type: "line"
        metrics: ["train/recall", "val/recall"]
      - name: "Kappa"
        type: "line"
        metrics: ["train/kappa", "val/kappa"]
      - name: "Learning Rate"
        type: "line"
        metric: "learning_rate"
      - name: "Attention Weights"
        type: "heatmap"
        metric: "attention_weights"
    
    performance:
      confusion_matrix:
        enabled: true
        frequency: 5
      roc_curve:
        enabled: true
      pr_curve:
        enabled: true
    
    logging:
      wandb: true
      save_checkpoints: true
      checkpoint_frequency: 1

evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "kappa"
  visualization:
    confusion_matrix: true
    roc_curve: true
    learning_curves: true
    attention_weights: true

