data:
  batch_size: 16
  cache_dir: data
  dataset_type: eegbci
  num_workers: 0
  preprocessing:
    high_freq: 30.0
    low_freq: 7.0
    stride: 160
    window_size: 320
  sampling_rate: 160
evaluation:
  metrics:
  - accuracy
  - precision
  - recall
  - f1
  - kappa
  visualization:
    confusion_matrix: true
    learning_curves: true
    roc_curve: true
    topographic_maps: true
model:
  chunk_size: 16
  dropout_rate: 0.5
  hidden_dim: 256
  input_channels: 64
  name: TitansEEG
  num_classes: 4
training:
  checkpoint_dir: runs\TitansEEG_20250213_225510\checkpoints
  early_stopping:
    min_delta: 0.001
    patience: 15
  epochs: 100
  learning_rate: 0.0003
  optimizer: adamw
  scheduler:
    T_max: 100
    eta_min: 1.0e-05
    name: cosine
  use_wandb: true
  weight_decay: 0.01
